dist: xenial
sudo: true

language: python
python: "3.7"

notifications:
  email:
    on_success: never
    on_failure: change 

install:
  - pip install -r requirements.txt

before_script:
  - python -m conan_inquiry find
  - python -m conan_inquiry generate
  - if [["$TRAVIS_BRANCH" == "master"]]; then python -m conan_inquiry deploy; fi
